name: test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "9.15.9"
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ">=22.14.0"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
